### ISSUE TITLE
OOM-kill on large PRs

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/opam-repo-ci#220]
https://github.com/ocaml/opam-repository/pull/23742 takes all of the 32GB of RAM of the server opam-repo-ci is running on and is just crashing and restarting in a loop.

**Comment by tmcgilchrist** [comment]
Additionally we noticed that the `Current_ocluster.Connection.pool`[1] being used to throttle the rate of job creation seems to be preventing jobs being created for non-busy pools of workers like linux-arm64 and macOS (basically anything that isn't linux-x86_64). I'm going to see if I can change that to be per pool and start submitting those jobs.

[1]: https://github.com/ocurrent/opam-repo-ci/blob/master/lib/build.ml#L177

**Comment by tmcgilchrist** [comment]
We have permanently moved the `opam-repo-ci` application to a machine with more RAM to avoid the Linux OOM-kill on large PRs. This new machine has significantly more resources (36 physical cores/72 with SMT and 515Gb RAM) which covers the peak RAM usage of 42Gb comfortably. Additionally the backlog of jobs for `opam-repo-ci` has reduced to a normal level, after a period of higher than usual load. Extra capacity was added to the cluster to help with this backlog. 

A full writeup of the incident will appear on http://infra.ocaml.org in the coming week.

**Comment by shonfeder** [comment]
Looks like this has been resolved for now.
