### ISSUE TITLE
Application and Operational Metrics

### ISSUE THREAD

**Issue by tmcgilchrist** [ocurrent/opam-repo-ci#221]
opam-repo-ci should report on application and operational level metrics via prometheus/grafana.

<img width="632" alt="upload_562ffa40fcdddb426eb9e15a9d2c6318" src="https://github.com/ocurrent/opam-repo-ci/assets/170937/9e367111-75d5-4389-b167-e967b7ba84fc">

- [x] Production dashboard in grafana for https://opam.ci.ocaml.org
- [x] Setup ocluster connection to export stats (it already supports prometheus)
- [x] Setup ocurrent to export stats (it already supports prometheus) (Size of the graph per PR)
- [x] Add ocurrent support for exporting Node creation/update/destroy metrics (as a proxy for graph size)

Non-exhaustive list of tasks to cover the monitoring of `opam-repo-ci` application.

**Comment by benmandrew** [comment]
I am still waiting on feedback and suggestions from `opam-repository` maintainers, but I am happy with the current state of the metrics and would be fine with closing this issue.

<img width="1425" alt="Screenshot 2023-12-12 at 12 58 06" src="https://github.com/ocurrent/opam-repo-ci/assets/13054139/b27789d0-d801-4889-bbfd-cdf722483311">

**Comment by tmattio** [comment]
Operational metrics were added to the Grafana dashboard and we agreed that they are sufficient to monitor the services for the time being. We might add more in the future if we see that more metrics are necessary.
