### ISSUE TITLE
Additional tests for opam-repo-ci

### ISSUE THREAD

**Issue by raphael-proust** [ocurrent/opam-repo-ci#264]
In https://github.com/ocaml/opam-repository/pull/25143 we realised there is a near-collision for package names: two packages where one has dashes (`-`) and the other underscores (`_`). We (the opam-repository maintainers) would like to avoid creating such near collisions. It would be good if the opam-repo-ci could add the following tests/outputs:

- When a new package file is added by a PR, and there is another package that has the same name except for non-alphanumerical characters, then there should be a warning in the CI (likely in the linting job?)

We also think it'd be nice to have additional warnings for names that are similar but not identical. Just to make typo-squatting more difficult.

- When a new package file is added by a PR, and there is another package that has a name with a low Levenshtein-distance from the newly published one, then there should be a warning in the CI. (Low would probably be 2 or 3.)

**Comment by benmandrew** [comment]
For the low Levenshtein distance warning, how do you propose the value of "low" be dependent on the overall length of the package name? Without this, packages that have names 3 or 4 characters long (of which there are many) will all fail their lint checks.

**Comment by raphael-proust** [comment]
The distance probably needs to only be checked after some threshold of length. I think ideally we would check the current distance distribution and then make some good guess about the appropriate threshold. As a gut feeling, I'd say the distance would be something like 1/6th. As in:

- For a package up to name-length 6, trigger a warning if there is a distance of 1.
- For a package up to name-length 12, trigger a warning if there is a distance of 2 or less.
- etc.

This might be a bit naive though… and maybe we need something fancy with a non-linear length-distance relation.

**Comment by benmandrew** [comment]
I'll have a go implementing it in a general way, so that we can easily tune the threshold if there's annoying false positives.

**Comment by benmandrew** [comment]
The Levenshtein distance check is not yet implemented.
