### ISSUE TITLE
Add linting check for new restricted prefixes

### ISSUE THREAD

**Issue by shonfeder** [ocurrent/opam-repo-ci#315]
Following https://github.com/ocaml/opam-repository/pull/25861, the opam repository aims to treat the following package name prefixes as restricted:

- `arch-`
- `system-`
- `host-`

The need linting rules added to the CI checks on opam files to raise an alert when package names start with one of these prefixes.

cc @raphael-proust and @kit-ty-kate

**Comment by benmandrew** [comment]
Another possible linting check that's being asked for is to check that a package has one of these prefixes iff it also has the corresponding `conflict-class` field.
