### ISSUE TITLE
Regression from use of `opam ---option` flag in tests

### ISSUE THREAD

**Issue by shonfeder** [ocurrent/opam-repo-ci#352]
Introduced by #351 

```
/home/opam: (run (shell "opam option solver=builtin-0install"))
opam: unknown command `option'.
Usage: opam COMMAND ...
Try `opam --help' for more information.
"/usr/bin/env" "bash" "-c" "opam option solver=builtin-0install" failed with exit status 2
2024-09-05 11:20.39: Job failed: Failed: Build failed
```

https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/8bb0696dddd93b63ad5a6ad3c5047beaa2d3bacf/variant/extras,opam-2.0-ocaml-4.14,gluten-lwt.0.5.2,tests

**Comment by mtelvers** [comment]
It's opam 2.0.10, so we need to update that to 2.2, which will help the timeout issue as well!
```
/home/opam: (run (shell "uname -rs && opam exec -- ocaml -version && opam --version"))
Linux 5.15.0-119-generic
The OCaml toplevel, version 4.14.2
2.0.10
```

**Comment by shonfeder** [comment]
Doing so! Thanks :)

**Comment by shonfeder** [comment]
I'm finding the code that sets the opam version quite tricky to follow. As a followup, I think this is probably worth a deep refactoring pass.

It *looks* like we are setting the opam version for all the obuilder specs at

https://github.com/shonfeder/opam-repo-ci/blob/e682604cd3f890291107f724d05e9e3896ed5be1/lib/build.ml#L9

But obviously something else is overriding this at some point, or we have another source of truth for which opam to use that only comes into effect on some platforms.

**Comment by shonfeder** [comment]
Ah, ok, it is coming from

https://github.com/ocurrent/opam-repo-ci/blob/e682604cd3f890291107f724d05e9e3896ed5be1/lib/build.ml#L156-L159

And the reason this is testing on opam < 2.2 is because these tests are meant to be testing the lower opam versions XD

**Comment by shonfeder** [comment]
So, iiuc, the only place where not already using the dev version is the place where we explicitly wanted to be testing older opam versions.

**Comment by mtelvers** [comment]
The alternative to `opam option solver=builtin-0install` is to use `env "OPAMEXTERNALSOLVER" "builtin-0install";` but that also gave problems.  I agree, let's revert until we have a better plan.

**Comment by shonfeder** [comment]
For now I can add a test so that this is only added when opam version is >= 2.2, and that may still reduce the timeouts, tho it can't clear up all of them.

Also, as per https://github.com/ocurrent/opam-repo-ci/pull/351#discussion_r1744361162, it's not clear that we want to use 0install on opam < 2.3

**Comment by mtelvers** [comment]
But it's likely that only opam < 2.2 have the problem.

**Comment by mtelvers** [comment]
How about increasing the timeout for the solver.  I looked at that previously: https://github.com/ocurrent/opam-repo-ci/pull/342

**Comment by shonfeder** [comment]
The quick fix I thought would work here is not doing so... :/ I'll revert to get this resolved in prod and let us work out a proper fix here, along with any refactoring necessary.

Longer timeout seems like a good stopgap.
