### ISSUE TITLE
OCaml 5.3 support

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/opam-repo-ci#363]
Requires to vendor https://github.com/ocurrent/ocaml-version/pull/74

**Comment by shonfeder** [comment]
We have done away with the vendoring in this repo as of https://github.com/ocurrent/opam-repo-ci/pull/349, so I think the proper order will be go get an update of `ocaml-version` released, and then update our dependency here.

**Comment by mtelvers** [comment]
5.3.0~alpha1 support added in https://github.com/ocurrent/opam-repo-ci/pull/365

**Comment by mtelvers** [comment]
#365 is merged and 5.3.0~alpha1 is now being tested.
