### ISSUE TITLE
Stalling after merging a PR

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/opam-repo-ci#80]
currently opam-repo-ci stalls after merging a PR and both the web-ui and main admin page return 405s for a few minutes after.
There is probably some code that takes a long time and doesn't use Lwt somewhere.
It seems this happened somewhere after the merge of https://github.com/ocurrent/opam-repo-ci/pull/70

**Comment by talex5** [comment]
Running `perf top` on `ci3` while this is happening might discover the problem.

**Comment by kit-ty-kate** [comment]
#81 fixed the issue
