### ISSUE TITLE
Change layout of Dockerfile for slightly easier debugging

### ISSUE THREAD

**Issue by dra27** [ocurrent/opam-repo-ci#83]
At the moment the instructions at the top of each run put the `Dockerfile` inside the `opam-repository` clone which means the `Dockerfile` becomes part of the image. Slightly neater would be: 

- Add a `cd ..` after the `git merge`
- `COPY --chown:1000:1000 opam-repository /src/`

and then editing the `Dockerfile` to poke and debug doesn't repeat the `COPY` each time

**Comment by kit-ty-kate** [comment]
Fixed in https://github.com/ocurrent/opam-repo-ci/pull/96
