### ISSUE TITLE
Download failure using opam lib

### ISSUE THREAD

**Issue by rjbou** [ocurrent/opam-repo-ci#93]
An assert failure is raised by `OpamDownload.download` [call](https://github.com/ocurrent/opam-repo-ci/blob/master/lib/lint.ml#L93) with a non http url.
original issue https://github.com/ocaml/opam-repository/pull/18455#issuecomment-814141706

**Comment by rjbou** [comment]
discussion from ocaml/opam-repository#18455

@dra27
>It would be easier to do be doing the equivalent of opam source here I think (I can't remember the API). The only change is opam is that arguably (pun intended) it should be an Invalid_arg not an assert.

@kit-ty-kate
> I tried to use the API used by opam source on Sunday, however this is inside the opam-client library which is currently incompatible with opam-repo-ci due to its transitive dependency on extlib (extlib < 1.7.8 and base64 cannot be used in the same project)

@dra27
>Is there any reason not to shell out to opam source directly? The API's not providing much benefit here - the download job shells out to curl (or git!) and the extract job shells out to tar.

**Comment by rjbou** [comment]
If you are not sure about the backend, you can use `OpamRepository.pull_tree` to retrieve sources

**Comment by kit-ty-kate** [comment]
Note that `opam lint` has the same issue:
```
/tmp/opam-repository/packages/sedlex/sedlex.1.99.1$ opam lint --check-upstream
/tmp/opam-repository/packages/sedlex/sedlex.1.99.1/opam: Errors.
  warning 47: Synopsis (or description first line) should start with a capital and not end with a dot
  warning 59: url doesn't contain a checksum
    error 60: Upstream check failed: "File "src/repository/opamDownload.ml", line 139, characters 2-8: Assertion failed"
```
